### ISSUE TITLE
Hey men thanks for the code but run into this

### ISSUE THREAD

**Issue by rink3y** [JasperAlexander/seaport-backend#2]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/codespace/.python/current/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/codespace/.local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/codespace/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 516, in check
    for pattern in self.url_patterns:
  File "/home/codespace/.local/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/codespace/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/seaport-backend/api/urls.py", line 13, in <module>
    path("api/v1/", include("api_orders.urls")),
  File "/home/codespace/.local/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/codespace/.python/current/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/seaport-backend/api_orders/urls.py", line 3, in <module>
    from . import views
  File "/workspaces/seaport-backend/api_orders/views.py", line 3, in <module>
    from .serializers import OrderReadSerializer, OrderWriteSerializer
  File "/workspaces/seaport-backend/api_orders/serializers.py", line 3, in <module>
    from api_orderparameters.serializers import OrderParametersSerializer, OrderParametersPublicSerializer
  File "/workspaces/seaport-backend/api_orderparameters/serializers.py", line 6, in <module>
    from drf_writable_nested.serializers import WritableNestedModelSerializer
ModuleNotFoundError: No module named 'drf_writable_nested'

**Comment by JasperAlexander** [comment]
Thank you for reporting this issue. I'm going to archive this repository because I don't have time to maintain it and it is too outdated.
